# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
  -
    id: "grmon"
    binary: grmon
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -ldflags=-s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 7

archives:
  -
    id: cpuid
    name_template: "grmon-{{ .Os }}_{{ .Arch }}_{{ .Version }}"
    replacements:
      aix: AIX
      darwin: OSX
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
      freebsd: FreeBSD
      netbsd: NetBSD
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^doc:'
    - '^docs:'
    - '^test:'
    - '^tests:'
    - '^Update\sREADME.md'
